server:
  port: 8761
spring:
  application:
    name: discoveryservice
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false